### ISSUE TITLE
Add an admin dashboard

### ISSUE THREAD

**Issue by graysonwright** [MattyAyOh/NimbusPOS#14]
This might be useful for setting product prices, viewing past orders, exporting as CSV, etc.

https://administrate-prototype.herokuapp.com/getting_started

**Comment by MattyAyOh** [comment]
This exists, http://nimbuspos.herokuapp.com/sales

Would be nice to have a way to aggregate everything, though

**Comment by graysonwright** [comment]
Aw, nah man. We're getting you a proper admin dashboard.

**Comment by MattyAyOh** [comment]
i can't afford it atm

i'm making labels for this repo

**Comment by graysonwright** [comment]
Boom.
nimbuspos.herokuapp.com/admin

<img width="800" alt="orders_-_karaoke" src="https://user-images.githubusercontent.com/829576/36519520-fbc48e88-1759-11e8-8d95-725bdc0eb1b2.png">
