### ISSUE TITLE
Test on a touchscreen

### ISSUE THREAD

**Issue by graysonwright** [MattyAyOh/NimbusPOS#15]
Might be that the buttons are too small to hit now.

We could get more screen real estate by shrinking the left side of the screen when you're editing an order.

**Comment by MattyAyOh** [comment]
I'll do this, I just bought this monitor

https://www.amazon.com/gp/product/B00CTODKIO/ref=od_aui_detailpages00?ie=UTF8&psc=1

Will report back how the app works on it

**Comment by MattyAyOh** [comment]
Was an issue with chrome, I reinstalled it and everything works great
