### ISSUE TITLE
Improve order summary page

### ISSUE THREAD

**Issue by graysonwright** [MattyAyOh/NimbusPOS#16]
It's kinda hard to tell what's going on. Since it's "invoice-y", it make more sense to display the info in a table.

<img width="217" alt="karaoke" src="https://user-images.githubusercontent.com/829576/35358193-ca06157a-0123-11e8-8f8d-454b6531cbca.png">

**Comment by MattyAyOh** [comment]
This likely will be made obsolete by my proposal in #21

**Comment by graysonwright** [comment]
Yep, taken care of by #21.
