### ISSUE TITLE
Make the time control more touch-friendly

### ISSUE THREAD

**Issue by MattyAyOh** [MattyAyOh/NimbusPOS#18]
Currently the control is not possible to set a time with a touch-screen, as it must be typed

You can press the "Start" "Stop" buttons to set the current time in, but sometimes they will need to manually input a time

![sdfdsfsd](https://user-images.githubusercontent.com/5342037/35427142-ad46072a-0235-11e8-801c-9f1bfccc028b.PNG)

**Comment by graysonwright** [comment]
![timepicker](https://user-images.githubusercontent.com/829576/36401838-39e85b76-15a8-11e8-9e1f-e36b74c8f412.gif)

**Comment by MattyAyOh** [comment]
hold on gotta go change my pants
