### ISSUE TITLE
Add ability to "Split Bill"

### ISSUE THREAD

**Issue by MattyAyOh** [MattyAyOh/NimbusPOS#22]
In checkout tab, add a "Split Bill" text field, if the user puts in 4, it will display how much needs to be charged by dividing the total by 4

**Comment by thecalliopecrashed** [comment]
This is in place already, yeah?
<img width="857" alt="Screen Shot 2019-05-13 at 5 30 58 PM" src="https://user-images.githubusercontent.com/30454698/57662572-e9da6080-75a4-11e9-99c5-af0329a2977f.png">
