### ISSUE TITLE
Add ability to count previous bills

### ISSUE THREAD

**Issue by MattyAyOh** [MattyAyOh/NimbusPOS#23]
In checkout tab, add a "previous bills"
The user can input a value here, and it will just add it to the total bill (but only visually, don't modify the model)

use case:
Kids use Pool4 and KTV4, start at same time
They close Pool4 an hour later, but continue to use KTV4
The user will checkout Pool4, note the total, and then input it into the "Previous bills" field in KTV4

Note: If each order has a Total Bill property, don't add the Previous Bills to it.
If kids played pool for an hour, their bill is $10
Then they decide to go sing, and not pay for their pool bill immediately

- Employee will checkout pool, take their total bill and remember it
- Employee will open a KTV room, and immediately input "Previous Charges" as $10

When they checkout the KTV room, 

- Employee will checkout KTV room, and their bill will get that $10 added to their total bill

In the admin portal, that extra $10 shouldn't be counted in total bill, because it was already counted when the employee checked out the pool table

**Comment by graysonwright** [comment]
So in your example, let's say the KTV room charge is $30.

Does this look right, then?

```
Pool bill: $10
Pool checkout: $0 cash handled

KTV bill: $30
KTV previous charge: $30
KTV checkout: $40 cash handled
```

**Comment by MattyAyOh** [comment]
Close, 
```
KTV bill: $30
KTV previous charge: $10
KTV total Bill: $40 
Cash Handled: $20
```

**Comment by thecalliopecrashed** [comment]
How about a button to "Migrate" a group to a new room/table?

We could add a button right next to "Checkout".
Clicking it would... ask you where they're migrating to.
Then you would tap one of the available rooms on the home screen, and it would add the new activity right into the existing bill for the group.

**Comment by MattyAyOh** [comment]
May be over-solving it, having a field to input a value also adds
flexibility, in case there is a debt like the employee forgot to checkin
the customer, or something like that

**Comment by MattyAyOh** [comment]
we'll just have them pay separately
