### ISSUE TITLE
Bug with wrapping time past midnight

### ISSUE THREAD

**Issue by MattyAyOh** [MattyAyOh/NimbusPOS#28]
say it's feb 1st, 10pm
3 hours later it's feb 2nd, 1am

but employee wants to change time to be 11:59PM, they will change it to be feb 2nd 11:59 instead of feb 1st

is there a solution to this?  A bill will never run past 4AM the next day, can we just assume any time inputted from 6PM-12AM counts as the date which the start time was started, 

and 12AM-11:59 AM counts as the date after the date where the start time was started?

Hm but what if it's like 2AM, feb 2nd, and the employee wants to go back and make the start time 9PM,  what happens?  Looks like it breaks

So actually this is probably best solution:
Check current time on machine
Have a variable for a stored date
If the current time is before 12AM, save the date into var
If the current time is after 12AM, decrement the date and save it into var

If employee enters a time between 6PM-12AM, set the date to be the value in the var
If the employee enters a time between 12AM-4AM, set the date to be the value in the var +1

**Comment by graysonwright** [comment]
I'm going to mark this as dependent on #36 - it will be easier to implement once we have the concept of the current time built into the frontend in a reasonable way.

Then we can copy/paste the logic that you outlined above.

**Comment by MattyAyOh** [comment]
This logic doesn't appear to work on the latest release, I ended up with a negative time spent value when the start time was 23:00, and the end time was 00:30

**Comment by graysonwright** [comment]
I think that bug ^ only shows up during a specific time of day. I just used 23:00 -> 00:30 and got `+1.5 hours` time spent.

I'll try to fake out the system time and see if I can get a negative time to appear.

**Comment by graysonwright** [comment]
It looks like you tried it at 11:30 pm, I tried it at 5:15 pm.

**Comment by graysonwright** [comment]
Likely fixed by #71, test it out at http://nimbuspos-pr-71.herokuapp.com

**Comment by MattyAyOh** [comment]
looks fixed by #71
