### ISSUE TITLE
Others doesn't load

### ISSUE THREAD

**Issue by MattyAyOh** [MattyAyOh/NimbusPOS#54]
![other](https://user-images.githubusercontent.com/5342037/36411885-a6175f8a-15e5-11e8-8253-5734406c4b89.PNG)

**Comment by graysonwright** [comment]
Yeah, I'd forgotten to populate those things in the database.

If you check again now, it's there.
<img width="383" alt="nimbus" src="https://user-images.githubusercontent.com/829576/36515009-6d5cfa22-1745-11e8-8e22-443b18168562.png">
