### ISSUE TITLE
Add button for current time, next to time control for end time

### ISSUE THREAD

**Issue by MattyAyOh** [MattyAyOh/NimbusPOS#55]
Pressing it automatically sets the time to the current time

![currenttime](https://user-images.githubusercontent.com/5342037/36412042-71133916-15e6-11e8-9884-bd031ffe0f88.png)

**Comment by MattyAyOh** [comment]
relies on #56

**Comment by graysonwright** [comment]
Is this still relevant after #34?

**Comment by MattyAyOh** [comment]
good call
