### ISSUE TITLE
Remove un-used times from time control, reorganize the options

### ISSUE THREAD

**Issue by MattyAyOh** [MattyAyOh/NimbusPOS#57]
These should be the hour options, in this order:

18
19
20
21
22
23
00
01
02
03
04

**Comment by graysonwright** [comment]
<img width="220" alt="banners_and_alerts_and_nimbus" src="https://user-images.githubusercontent.com/829576/36514442-6e418c58-1742-11e8-80ae-ff28f6fa33e7.png">
