### ISSUE TITLE
Password-protect the site

### ISSUE THREAD

**Issue by graysonwright** [MattyAyOh/NimbusPOS#63]
See http://api.rubyonrails.org/classes/ActionController/HttpAuthentication/Basic.html

**Comment by MattyAyOh** [comment]
lol at meijer now, but is this really solvable by one commit? interested to
see what you came up with

**Comment by graysonwright** [comment]
@MattyAyOh 

Before people use it, remember to:

```
heroku config:set PASSWORD=a_new_password --app nimbuspos
```
