### ISSUE TITLE
End Time flow is buggy, around checkout

### ISSUE THREAD

**Issue by MattyAyOh** [MattyAyOh/NimbusPOS#64]
This works:
1) Open room, start time automatically is set (Good)
2) Don't set end time, go to checkout, end time is set automatically (Good)

Here is the flow that is funny:
1) Open room, start time automatically is set (Good)
2) Manually set End Time, press checkout, values don't update
3) Switching orders doesn't refresh the start and end time fields

Also you can't delete the end time field, it will say Invalid Date

**Comment by graysonwright** [comment]
I'm confused by:

> Manually set End Time, press checkout, values don't update

Do you want checkout to *always* set the end time, even when it's already been set?
If so, that would wipe out any time the employee has already entered.

**Comment by graysonwright** [comment]
I think I sorted out:

> Switching orders doesn't refresh the start and end time fields

in #69.

**Comment by MattyAyOh** [comment]
Yeah it looks like after your two PRs this is resolved, but I'm not 100%

I'm still seeing random times where setting start/end time doesn't stick, I'll provide exact repro steps after we get these branches in

Also, 

> I'm confused by:
> 

> > Manually set End Time, press checkout, values don't update

> 
> Do you want checkout to always set the end time, even when it's already been set?
> If so, that would wipe out any time the employee has already entered.

er right, don't wipe out the time the employee entered,
i meant the "values" as in the checkout page, it wouldn't update the price correctly

looks fixed by #71 though

**Comment by MattyAyOh** [comment]
This is fixed by #69 and #71
