### ISSUE TITLE
Confirm button broken?

### ISSUE THREAD

**Issue by MattyAyOh** [MattyAyOh/NimbusPOS#65]
Not sure if I broke it, but refresh, switching tabs, etc doesn't seem to fix it

It's just un-clickable on production right meow

**Comment by graysonwright** [comment]
Just tried it in production:

![confirm](https://user-images.githubusercontent.com/829576/36634136-115d935a-196e-11e8-97d1-803520f857e5.gif)

It seems to work if all of the fields are filled out.
If you skip any fields, though - it fails with no feedback.

I'll dim it out until all the fields are filled out, like you mentioned on the phone.

**Comment by MattyAyOh** [comment]
ooo gotcha

**Comment by graysonwright** [comment]
![confirm](https://user-images.githubusercontent.com/829576/36868194-9aa89a88-1d65-11e8-9ddf-a3a6c04f2327.gif)

**Comment by graysonwright** [comment]
^ The confirm button is now deactivated until it's clickable.

The confirm button is also now a button. ツ
