### ISSUE TITLE
Don't require cash handled for the confirm button enabling

### ISSUE THREAD

**Issue by MattyAyOh** [MattyAyOh/NimbusPOS#72]
I think the confirm button should only be disabled if the start time is past the end time

Other than that, we already have it so if there is no end time, clicking Checkout will automatically set the end time

and otherwise the user will have already set the end time

**Comment by thecalliopecrashed** [comment]
The "Cash Handled" field has been gone for a while - see 310430ecb994e1b938f79438cf0174ac25174a08.

I'm removing the remaining references to it from the database, etc.
