### ISSUE TITLE
Auto-boot to the bigscreen site on a raspberry pi.

### ISSUE THREAD

**Issue by thecalliopecrashed** [MattyAyOh/NimbusPOS#85]
1. Set up a raspberry pi with Desktop Raspbian.
2. Plug in USB keyboard, ethernet.
3. With your text editor of choice, create `~/.config/autostart/bigscreen.desktop` with:

```txt
[Desktop Entry]
Type=Application
Exec=/usr/bin/chromium-browser --kiosk --disable-restore-session-state --incognito "http://142.93.196.155/bigscreen"
Hidden=false
X-GNOME-Autostart-enabled=true
Name[en_US]=bigscreenName=bigscreenComment=Display the Nimbus menu when the Pi is plugged in.
```

4. Following [this advice](https://www.opentechguides.com/how-to/article/raspberry-pi/28/raspi-display-setting.html), set:

```txt
disable_overscan=1
# Delete or comment out the other overscan lines
```

**Comment by MattyAyOh** [comment]
Is this not what is happening now?

**Comment by thecalliopecrashed** [comment]
I think this is working now - I'll mark it as "documentation" in case we need to re-create the setup.

**Comment by c4lliope** [comment]
Updated page address; `http://nimbus-sales.herokuapp.com/bigscreen`

**Comment by MattyAyOh** [comment]
nice :+1:
