### ISSUE TITLE
Remove "Milk Tea - Bottle" from Extras

### ISSUE THREAD

**Issue by MattyAyOh** [MattyAyOh/NimbusPOS#87]

**Comment by thecalliopecrashed** [comment]
Hm, I don't see it in there right now.

We've got:
```
Instant Ramen
Fish Tofu
Lonely God
Shrimp Flakes
Beancurd
Pocky
GGE
Yan Yan
Tiramisu
Choco Pie
Cookie
Calpico
Milk Drink
Coconut Milk
Lemon Ice Box
Green Tea Bottle
Pear Juice
Fanta
Sprite
Coke
Diet Coke
Milki
Lemon Box
Bottled Water
Hot Tea
Playing Cards
Stickiness
Puke
Burns
```

**Comment by mattyayoh-b** [comment]
Snacks
---
Fish Tofu
Lonely God
Shrimp Flakes
Beancurd
Pocky
GGE
Custard Pie
Choco Pie

Drinks
---
Aloe
Calpico
Milk Drink
Coconut Milk
Lemon Ice Box
Green Tea Bottle
Fanta
Sprite
Coke
Milki
Lemon Box
Bottled Water

Misc.
----
Playing Cards 
Stickiness 
Puke 
Burns

**Comment by thecalliopecrashed** [comment]
Just confirmed that this is what's in our database.

Only exception is that here you list "Lemon Ice Box" and "Lemon Box"; the database now replaces those with "Lemon Iced Tea", per Charlie's request.
