### ISSUE TITLE
Improve deploy script to manage a permanent production environment

### ISSUE THREAD

**Issue by MattyAyOh** [MattyAyOh/NimbusPOS#91]
Migrated from Wunderlist

**Comment by thecalliopecrashed** [comment]
Best practices right now are captured in https://github.com/uwcirg/tb-mobile-app/blob/mocks/bin/deploy .

This will slowly improve over time.
I'll leave this open with the "documentation" label, so we have a place to note changes.

**Comment by thecalliopecrashed** [comment]
These instructions are now captured in the last section of the README.
